import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'database_helper.dart';

class ExportService {
  // FR34: Generate & Export PDF Inspection Report
  static Future<void> exportPdfReport(ResultRecord record) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Padding(
            padding: const pw.EdgeInsets.all(24),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Header(
                  level: 0,
                  child: pw.Row(
                    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                    children: [
                      pw.Text('Aloe Vera Inspection Quality Report', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
                      pw.Text(record.leafId, style: const pw.TextStyle(fontSize: 14, color: PdfColors.grey700)),
                    ],
                  ),
                ),
                pw.SizedBox(height: 16),
                pw.Text('Timestamp: ${record.timestamp}'),
                pw.Divider(),
                pw.SizedBox(height: 16),

                // Summary Table
                pw.TableHelper.fromTextArray(
                  context: context,
                  data: <List<String>>[
                    <String>['Parameter', 'Measurement / Result'],
                    <String>['Final Inspection Grade', record.finalGrade],
                    <String>['Disease Status', record.diseaseDetected],
                    <String>['AI Confidence Score', '${record.confidenceScore}%'],
                    <String>['Green Color Hue', '${record.greenColorPct}%'],
                    <String>['Yellowing / Browning', '${record.yellowBrowningPct}%'],
                    <String>['Physical Damage Ratio', '${record.physicalDamagePct}% (${record.damageType})'],
                  ],
                ),

                pw.SizedBox(height: 20),
                pw.Text('Grading Assessment & Justification:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 6),
                pw.Text(record.gradingReason),

                pw.Spacer(),
                pw.Divider(),
                pw.Center(
                  child: pw.Text('Generated by Aloe Vera AI Quality Inspection System'),
                ),
              ],
            ),
          );
        },
      ),
    );

    await Printing.sharePdf(
      bytes: await pdf.save(),
      filename: 'Inspection_Report_${record.leafId}.pdf',
    );
  }
}